POST    http://localhost:3000/api/v1/task/
Content-Type: application/json

{
    "description": " Ulepszony task"
}
###
GET http://localhost:5000/api/v1/task/

###

GET  https://hardworkapp.herokuapp.com/api/v1/task


###
POST http://localhost:3000/api/users/register
Content-Type: application/json

{
    "Name": "Adam",
    "Email": "adkowal777@gmail.com",
    "Password": "1234"
}