PATCH     http://localhost:3001/api/v1/task/2
Content-Type: application/json

{
  "done": true
}

###
GET http://localhost:3001/api/v1/task/list/




###

POST http://localhost:3001/api/v1/task/list
Content-Type: application/json

{
    "name": "dsadas" 
}
### del
DELETE http://localhost:3001/api/v1/task/list/12

### REGISTER
GET http://localhost:3001/api/v1/task/list/1
Content-Type: application/json

{
    "description":"Dzika strefa rozrywki"
}


### LOGOUT
DELETE http://localhost:5000/api/v1/auth/logout
